// ============================================================
// core.test.ts — Compilation and content assertions for the
// public entry (src/scss/main.scss) and the demo entry
// (src/scss/demo.scss).
//
// Deterministic: compiles in memory via the sass JS API
// (sass.compile with an absolute path). No network, no git,
// read-only over src/ and dist/.
// ============================================================

import { describe, it } from 'vitest';
import assert from 'node:assert/strict';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as sass from 'sass';

const PROJECT_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const MAIN_ENTRY = path.join(PROJECT_ROOT, 'src', 'scss', 'main.scss');
const DEMO_ENTRY = path.join(PROJECT_ROOT, 'src', 'scss', 'demo.scss');
const LOAD_PATHS = [path.join(PROJECT_ROOT, 'src', 'scss')];

let mainCss: string | null = null;
let demoCss: string | null = null;

function getMainCss(): string {
  if (mainCss === null) {
    mainCss = sass.compile(MAIN_ENTRY, { loadPaths: LOAD_PATHS }).css;
  }
  return mainCss;
}

function getDemoCss(): string {
  if (demoCss === null) {
    demoCss = sass.compile(DEMO_ENTRY, { loadPaths: LOAD_PATHS }).css;
  }
  return demoCss;
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function expectCompiles(entry: string, compile: () => string): void {
  let css: string;
  try {
    css = compile();
  } catch (error) {
    assert.fail(`compiling ${entry} failed: ${errorMessage(error)}`);
  }
  assert.ok(css.length > 0, `compiled CSS of ${entry} should not be empty`);
}

describe('core: public entry (src/scss/main.scss)', () => {
  it('should compile without errors', () => {
    expectCompiles(MAIN_ENTRY, getMainCss);
  });

  it('should include the color utility classes', () => {
    const css = getMainCss();
    for (const selector of ['.bg-neutral-100', '.text-neutral-500']) {
      assert.ok(css.includes(selector), `expected CSS to contain "${selector}"`);
    }
  });

  it('should include the sizing, spacing and layout utilities', () => {
    const css = getMainCss();
    const checks: [string, string | null][] = [
      ['.w-screen', 'width: 100vw'],
      ['.p-05', null],
      ['.p-1-5', null],
      ['.p-base', null],
      ['.hidden', 'display: none'],
      ['.font-normal', 'font-weight: 400'],
    ];
    for (const [selector, property] of checks) {
      assert.ok(css.includes(selector), `expected CSS to contain "${selector}"`);
      if (property !== null) {
        assert.ok(
          css.includes(property),
          `expected CSS to contain "${property}" (for "${selector}")`,
        );
      }
    }
  });

  it('should emit design tokens and color custom properties in :root', () => {
    const css = getMainCss();
    assert.ok(css.includes(':root'), 'expected a :root block');
    const tokens = [
      '--font-sans-serif',
      '--shadow-md',
      '--spacing-4',
      '--container-xl',
      '--z-tooltip',
      '--duration-200',
      '--ease-in-out',
      '--neutral-100:',
      '--white:',
    ];
    for (const token of tokens) {
      assert.ok(css.includes(token), `expected CSS to contain token "${token}"`);
    }
  });

  it('should include the utilities generated by generate-all-utilities', () => {
    const css = getMainCss();
    assert.match(
      css,
      /\.flex\s*\{[^}]*display:\s*flex/,
      'expected a .flex class with display: flex',
    );
    for (const selector of ['.items-center', '.shadow-lg', '.z-10']) {
      assert.ok(css.includes(selector), `expected CSS to contain "${selector}"`);
    }
  });

  it('should not contain remnants of the previous identity', () => {
    const css = getMainCss();
    const forbidden = [
      'basque',
      'ceuta',
      'melilla',
      'aragon',
      'asturias',
      'baleares',
      'slate',
      'amber',
      '--reen-basque',
    ];
    for (const word of forbidden) {
      assert.ok(
        !css.includes(word),
        `expected CSS to NOT contain "${word}" (legacy identity remnant)`,
      );
    }
  });
});

describe('core: demo entry (src/scss/demo.scss)', () => {
  it('should compile without errors', () => {
    expectCompiles(DEMO_ENTRY, getDemoCss);
  });

  it('should include the example components', () => {
    const css = getDemoCss();
    for (const selector of ['.card', '.button']) {
      assert.ok(css.includes(selector), `expected CSS to contain "${selector}"`);
    }
  });

  it('should include the responsive md breakpoint from components', () => {
    const css = getDemoCss();
    assert.ok(
      css.includes('@media (min-width: 768px)'),
      'expected a @media query with 768px from the components',
    );
  });
});
